### ISSUE TITLE
python mainCode.py 提示错误

### ISSUE THREAD

**Issue by IMNewJobFirst** [munanfan/Mahjong_Game_RLCard_RL#1]
Python 3.10.7
使用 python mainCode.py

True, 0, [4, 0, 1, 0])
True
[4, 2, 1, 0]
##########################
No Legal Actions
(True, 0, [4, 0, 1, 0])
True
[4, 2, 1, 0]
##########################
No Legal Actions
(True, 0, [4, 0, 1, 0])
True
[4, 2, 1, 0]
epoch: 268 / 50000, env: env_learn
epoch: 269 / 50000, env: env_learn
epoch: 270 / 50000, env: env_learn
epoch: 271 / 50000, env: env_learn
epoch: 272 / 50000, env: env_learn
epoch: 273 / 50000, env: env_learn
epoch: 274 / 50000, env: env_learn
epoch: 275 / 50000, env: env_learn
epoch: 276 / 50000, env: env_learn
epoch: 277 / 50000, env: env_learn
epoch: 278 / 50000, env: env_learn
epoch: 279 / 50000, env: env_learn
epoch: 280 / 50000, env: env_learn
epoch: 281 / 50000, env: env_learn
epoch: 282 / 50000, env: env_learn
epoch: 283 / 50000, env: env_learn
epoch: 284 / 50000, env: env_learn
epoch: 285 / 50000, env: env_learn
epoch: 286 / 50000, env: env_learn
epoch: 287 / 50000, env: env_learn
epoch: 288 / 50000, env: env_learn
epoch: 289 / 50000, env: env_learn
epoch: 290 / 50000, env: env_learn
epoch: 291 / 50000, env: env_learn
epoch: 292 / 50000, env: env_learn
epoch: 293 / 50000, env: env_learn
epoch: 294 / 50000, env: env_learn
epoch: 295 / 50000, env: env_learn
epoch: 296 / 50000, env: env_learn
epoch: 297 / 50000, env: env_learn
epoch: 298 / 50000, env: env_learn
epoch: 299 / 50000, env: env_learn
epoch: 300 / 50000, env: env_learn

----------------------------------------
  episode      |  19090
  reward       |  0.02
----------------------------------------
epoch: 301 / 50000, env: env_learn
epoch: 302 / 50000, env: env_learn
epoch: 303 / 50000, env: env_learn
epoch: 304 / 50000, env: env_learn
epoch: 305 / 50000, env: env_learn
epoch: 306 / 50000, env: env_learn
epoch: 307 / 50000, env: env_learn
epoch: 308 / 50000, env: env_learn
epoch: 309 / 50000, env: env_learn
epoch: 310 / 50000, env: env_learn
epoch: 311 / 50000, env: env_learn
epoch: 312 / 50000, env: env_learn
epoch: 313 / 50000, env: env_learn
epoch: 314 / 50000, env: env_learn
epoch: 315 / 50000, env: env_learn
epoch: 316 / 50000, env: env_learn
epoch: 317 / 50000, env: env_learn
epoch: 318 / 50000, env: env_learn
epoch: 319 / 50000, env: env_learn
epoch: 320 / 50000, env: env_learn
epoch: 321 / 50000, env: env_learn
epoch: 322 / 50000, env: env_learn
epoch: 323 / 50000, env: env_learn
epoch: 324 / 50000, env: env_learn
epoch: 325 / 50000, env: env_learn
epoch: 326 / 50000, env: env_learn
epoch: 327 / 50000, env: env_learn
epoch: 328 / 50000, env: env_learn
epoch: 329 / 50000, env: env_learn
epoch: 330 / 50000, env: env_learn
epoch: 331 / 50000, env: env_learn
epoch: 332 / 50000, env: env_learn
epoch: 333 / 50000, env: env_learn
epoch: 334 / 50000, env: env_learn
epoch: 335 / 50000, env: env_learn
epoch: 336 / 50000, env: env_learn
epoch: 337 / 50000, env: env_learn
epoch: 338 / 50000, env: env_learn
epoch: 339 / 50000, env: env_learn
epoch: 340 / 50000, env: env_learn
epoch: 341 / 50000, env: env_learn
epoch: 342 / 50000, env: env_learn
epoch: 343 / 50000, env: env_learn
epoch: 344 / 50000, env: env_learn
epoch: 345 / 50000, env: env_learn
epoch: 346 / 50000, env: env_learn
epoch: 347 / 50000, env: env_learn
epoch: 348 / 50000, env: env_learn

Logs saved in /Users/bd/mj/Mahjong_Game_RLCard_RL/Logger
Traceback (most recent call last):
  File "/Users/bd/mj/Mahjong_Game_RLCard_RL/mainCode.py", line 151, in <module>
    run(args)
  File "/Users/bd/mj/Mahjong_Game_RLCard_RL/mainCode.py", line 123, in run
    duel_agent.feed(ts)
  File "/Users/bd/mj/Mahjong_Game_RLCard_RL/Agent/DuelDQNAgent.py", line 103, in feed
    self.train()
  File "/Users/bd/mj/Mahjong_Game_RLCard_RL/Agent/DuelDQNAgent.py", line 162, in train
    state_batch, action_batch, reward_batch, next_state_batch, legal_actions_batch, done_batch = self.memory.sample()
ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (512,) + inhomogeneous part.

是参数需要调整吗？谢谢！

**Comment by Waiyva** [comment]
@IMNewJobFirst 请问你解决了吗，出现了同样的错误，能否提供帮助
